### ISSUE TITLE
Inflate Exception in xml

### ISSUE THREAD

**Issue by ram-ap** [dmytrodanylyk/android-process-button#16]
Hai.. 
         I am trying to run your sample project. I got this error. Please help me solve this issue.

```
07-15 11:26:24.416: E/AndroidRuntime(3195): FATAL EXCEPTION: main
07-15 11:26:24.416: E/AndroidRuntime(3195): Process: com.example.processbutton, PID: 3195
07-15 11:26:24.416: E/AndroidRuntime(3195): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.processbutton/com.example.processbutton.MainActivity}: android.view.InflateException: Binary XML file line #25: Error inflating class com.dd.processbutton.iml.SubmitProcessButton
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.app.ActivityThread.access$800(ActivityThread.java:139)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.os.Handler.dispatchMessage(Handler.java:102)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.os.Looper.loop(Looper.java:136)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.app.ActivityThread.main(ActivityThread.java:5086)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at java.lang.reflect.Method.invokeNative(Native Method)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at java.lang.reflect.Method.invoke(Method.java:515)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at dalvik.system.NativeStart.main(Native Method)
07-15 11:26:24.416: E/AndroidRuntime(3195): Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class com.dd.processbutton.iml.SubmitProcessButton
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.app.Activity.setContentView(Activity.java:1937)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at com.example.processbutton.MainActivity.onCreate(MainActivity.java:16)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.app.Activity.performCreate(Activity.java:5248)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
07-15 11:26:24.416: E/AndroidRuntime(3195):     ... 11 more
07-15 11:26:24.416: E/AndroidRuntime(3195): Caused by: java.lang.reflect.InvocationTargetException
07-15 11:26:24.416: E/AndroidRuntime(3195):     at java.lang.reflect.Constructor.constructNative(Native Method)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
07-15 11:26:24.416: E/AndroidRuntime(3195):     ... 23 more
07-15 11:26:24.416: E/AndroidRuntime(3195): Caused by: java.lang.NoClassDefFoundError: com.dd.processbutton.R$styleable
07-15 11:26:24.416: E/AndroidRuntime(3195):     at com.dd.processbutton.FlatButton.initAttributes(FlatButton.java:45)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at com.dd.processbutton.FlatButton.init(FlatButton.java:38)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at com.dd.processbutton.FlatButton.<init>(FlatButton.java:27)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at com.dd.processbutton.ProcessButton.<init>(ProcessButton.java:31)
07-15 11:26:24.416: E/AndroidRuntime(3195):     at com.dd.processbutton.iml.SubmitProcessButton.<init>(SubmitProcessButton.java:40)
07-15 11:26:24.416: E/AndroidRuntime(3195):     ... 26 more
```

**Comment by chigup** [comment]
Im also getting same error im using android studio

here is the java file

it is showing me error on setContentView

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_personal_data);

        

> Process: com.teepe.teepe, PID: 13426
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.teepe.teepe/com.teepe.teepe.KYC.personalData}: android.view.InflateException: Binary XML file line #212: Binary XML file line #212: Error inflating class com.dd.CircularProgressButton
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: android.view.InflateException: Binary XML file line #212: Binary XML file line #212: Error inflating class com.dd.CircularProgressButton
     Caused by: android.view.InflateException: Binary XML file line #212: Error inflating class com.dd.CircularProgressButton
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
