### ISSUE TITLE
Binary XML file line #212: Binary XML file line #212: Error inflating class com.dd.CircularProgressButton

### ISSUE THREAD

**Issue by chigup** [dmytrodanylyk/android-process-button#66]
Im also getting same error im using android studio

here is the java file

it is showing me error on setContentView

`@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_personal_data);`

> Process: com.teepe.teepe, PID: 13426
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.teepe.teepe/com.teepe.teepe.KYC.personalData}: android.view.InflateException: Binary XML file line #212: Binary XML file line #212: Error inflating class com.dd.CircularProgressButton
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: android.view.InflateException: Binary XML file line #212: Binary XML file line #212: Error inflating class com.dd.CircularProgressButton
Caused by: android.view.InflateException: Binary XML file line #212: Error inflating class com.dd.CircularProgressButton

**Comment by youtzz** [comment]
This project is not compatible with andriodX
